### PR TITLE
Maddi @ Ansarada's first pass at a bot

### PR DESCRIPTION
**Pull request by madeleinemila**

### CODE REVIEW

**Comment by dominikwilkowski** [comment]
Awesome! Outside contribution. I will run your bot with the others right after round 2 @madeleinemila :)

**Comment by madeleinemila** [comment]
thanks heaps @dominikwilkowski :)  i'm a junior so i'm thinking my little bot is going to get smashed, but this was a really fun challenge, looking forward to being involved.

**Comment by dominikwilkowski** [comment]
Hey @madeleinemila 

Your bot did very well. After running the game for 1mio games these are the scores:

```
🎉   WINNERS  🎉

100% done
 13.900%    108844.50   TimL
 12.194%     84944.20   JohnM
 11.758%     83510.90   JossM
  9.862%     59040.30   TuanH
  9.703%     54404.60   AbbasA
  9.405%     52375.50   Madds
  8.893%     48883.60   DomW
  8.707%     45939.80   MikeH
  6.671%     19437.90   TomW
  6.109%     14797.90   NathS
  2.391%    -28395.80   BenC
  1.289%    -41659.00   TiciA
  0.468%    -51385.80   SanjiyaD
  0.238%    -54302.80   MikeG
  0.044%    -56502.60   LaurenA
  0.047%    -56528.20   CharlesL
  0.047%    -56616.40   KevinY
  0.044%    -56640.60   JedW
  0.040%    -56671.60   BorisB
  0.046%    -56693.40   MalB
  0.043%    -56783.00   JessT
```

FYI I have an array in my bot that sorts other bots and because I did not account for you I constanlty called you for bluffing and that knocked me down big time :)

**Comment by madeleinemila** [comment]
woohoo! so excited, go little bot. sorry for tricking your bot ;)

**Pull request merged**
